import * as Utils from "~core/common/util";

// FETCH
export const FETCH_TODO = 'FETCH_TODO';
export const FETCH_TODO_REQUEST = Utils.REQUEST(FETCH_TODO);
export const FETCH_TODO_SUCCESS = Utils.SUCCESS(FETCH_TODO);
export const FETCH_TODO_FAILURE = Utils.FAILURE(FETCH_TODO);

// ADD
export const ADD_TODO = 'ADD_TODO';
export const ADD_TODO_REQUEST = Utils.REQUEST(ADD_TODO);
export const ADD_TODO_SUCCESS = Utils.SUCCESS(ADD_TODO);
export const ADD_TODO_FAILURE = Utils.FAILURE(ADD_TODO);

// REMOVE
export const REMOVE_TODO = 'REMOVE_TODO';
export const REMOVE_TODO_REQUEST = Utils.REQUEST(REMOVE_TODO);
export const REMOVE_TODO_SUCCESS = Utils.SUCCESS(REMOVE_TODO);
export const REMOVE_TODO_FAILURE = Utils.FAILURE(REMOVE_TODO);

// TOGGLE
export const TOGGLE_TODO = 'TOGGLE_TODO';
export const TOGGLE_TODO_REQUEST = Utils.REQUEST(TOGGLE_TODO);
export const TOGGLE_TODO_SUCCESS = Utils.SUCCESS(TOGGLE_TODO);
export const TOGGLE_TODO_FAILURE = Utils.FAILURE(TOGGLE_TODO);

// TOGGLE_ALL
export const TOGGLE_ALL_TODO = 'TOGGLE_ALL_TODO';
export const TOGGLE_ALL_TODO_REQUEST = Utils.REQUEST(TOGGLE_ALL_TODO);
export const TOGGLE_ALL_TODO_SUCCESS = Utils.SUCCESS(TOGGLE_ALL_TODO);
export const TOGGLE_ALL_TODO_FAILURE = Utils.FAILURE(TOGGLE_ALL_TODO);

// EDIT TITLE
export const EDIT_END_TODO = 'EDIT_END_TODO';
export const EDIT_END_TODO_REQUEST = Utils.REQUEST(EDIT_END_TODO);
export const EDIT_END_TODO_SUCCESS = Utils.SUCCESS(EDIT_END_TODO);
export const EDIT_END_TODO_FAILURE = Utils.FAILURE(EDIT_END_TODO);

// FILTER TODO
export const FILTER_TODO = 'FILTER_TODO';

// CLEAR COMPLETED
export const CLEAR_COMPLETED_TODO = 'CLEAR_COMPLETED_TODO';
export const CLEAR_COMPLETED_TODO_REQUEST = Utils.REQUEST(CLEAR_COMPLETED_TODO);
export const CLEAR_COMPLETED_TODO_SUCCESS = Utils.SUCCESS(CLEAR_COMPLETED_TODO);
export const CLEAR_COMPLETED_TODO_FAILURE = Utils.FAILURE(CLEAR_COMPLETED_TODO);

// SOCKET_NOTIFIED
export const SOCKET_NOTIFIED_TODO = 'SOCKET_NOTIFIED_TODO';
export const SOCKET_NOTIFIED_TODO_REQUEST = Utils.REQUEST(SOCKET_NOTIFIED_TODO);
export const SOCKET_NOTIFIED_TODO_SUCCESS = Utils.SUCCESS(SOCKET_NOTIFIED_TODO);
export const SOCKET_NOTIFIED_TODO_FAILURE = Utils.FAILURE(SOCKET_NOTIFIED_TODO);
